services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
    - "7463:7463"
    environment:
    - MONGO_URL=${MONGO_URL}
    - REDIS_URL=redis://redis_db:6379
    - SECRET=${SECRET}
    - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
    - mongo_db
    - redis_db
  crypto_worker:
      build:
        context: ./backend/crypto_service
        dockerfile: dockerfile
      environment:
        - REDIS_URL=redis://redis_db:6379
      depends_on:
        - redis_db
  mongo_db:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
  
  redis_db:
    image: redis:alpine

volumes:
  mongo_data: